M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-05-24T16:29:10+0330
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-24T16:29:10+03:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X3.6848Y-0.8508
X3.6848Y-1.024
M30
