M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-05-24T20:02:36+0330
; FORMAT={3:3/ absolute / metric / suppress trailing zeros}
; #@! TF.CreationDate,2024-05-24T20:02:36+03:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,LZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X093595Y-02161
X093595Y-02601
M30
